# Generated by Django 2.2.6 on 2022-04-13 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='First Name')),
                ('summary', models.TextField(max_length=255, verbose_name='summary')),
                ('author', models.TextField(max_length=255, verbose_name='Author')),
                ('Book_code', models.CharField(max_length=255, unique=True, verbose_name='Book Code')),
                ('no_of_book', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
