# Generated by Django 2.2.6 on 2022-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_code',
            new_name='book_code',
        ),
    ]
